name: hesabo_chat_ai
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  scrollable_positioned_list: ^0.3.8
  get_it: ^8.0.3
  flutter_dotenv: ^5.1.0
  responsive_framework: ^1.5.1
  bot_toast: ^4.1.3
  rxdart: ^0.28.0
  intl: ^0.20.2
  ficonsax: ^0.0.3
  flutter_svg: ^2.1.0
  skeleton_text: ^3.0.1
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  permission_handler: ^12.0.0+1
  flutter_sms_inbox: ^1.0.4
  shamsi_date: ^1.1.0
  gpt_markdown: ^1.1.1
#  serious_python: ^0.9.2
  api_handler:
    git: { url: 'https://github.com/ardeshir-33033/api_helper.git', ref: main }

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - production.env
    - app/python_code.zip
    - assets/images/banks/
  fonts:
    - family: IRANYekanXFaNum
      fonts:
        - asset: assets/font/IRANYekanXFaNum-Light.ttf
          weight: 300
        - asset: assets/font/IRANYekanXFaNum-Regular.ttf
          weight: 400
        - asset: assets/font/IRANYekanXFaNum-Medium.ttf
          weight: 500
        - asset: assets/font/IRANYekanXFaNum-Bold.ttf
          weight: 800
        - asset: assets/font/IRANYekanXFaNum-Black.ttf
          weight: 900


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
